### PR TITLE
fix: Reduce space between searchbar and table

### LINKED ISSUE #1492: Table with Search Bar has wastage of space
#### Is your feature request related to a problem? Please describe
A table with a search bar leads to a large wasted space between the bar and the table.

#### Describe the solution you'd like
A much smaller gap to utilize maximum space.

Screenshot 2022-06-09 at 6 26 12 PM

### PR DESCRIPTION
**Pull request by JacksonIsaac**
# Github Issue
Fixes #1492 

## Before 
image

## After
image

#### With pixel spacing dimension

image

image

#### Side by side (groupby and search)

image
image

### CODE REVIEW

**Comment by mturoci** [comment]
How big is the gap? It would be great if it was exactly `15px`. Also can you also include screenshots of:

* Just searchbar - already included.
* Just groupby
* Searchbar + groupby together.

We need to make sure all these are consistent and have the same vertical spacing.

**Comment by JacksonIsaac** [comment]
I have added screenshots for the pixel dimension between search/groupby bar and the table. The gap for searchbar is ~16px and for groupby is ~15px. I tried few different parameters, but this was the best I could get for them.

**Comment by mturoci** [comment]
> The gap for searchbar is ~16px and for groupby is ~15px

Unfortunately, that's not good enough since they can be also displayed side by side in which case, it will not look good.

**Comment by JacksonIsaac** [comment]
@mturoci how can I try that scenario where both are used side by side ? Do you perhaps have an example maybe ?

**Comment by mturoci** [comment]
`table.py` should have them both IIRC.

**Comment by JacksonIsaac** [comment]
When put together, in table.py example both search and groupby had exact space of 15px

image

**Review by mturoci — APPROVED** [review]
Thanks @JacksonIsaac!

**Pull request merged**
