### PR TITLE
feat: Sidebar improvements

### LINKED ISSUE #1118: Sidebar improvements
#### Is your feature request related to a problem? Please describe

Wave currently supports only header where title, subtitle, and menu can be specified. However, some apps may want to use side nav menu only, but still keep the branding.

#### Describe the solution you'd like

Allow people to use a layout like:
image
image

#### Proposed API

There are 2 options, either go with a new `ui.side_nav` card or enhance the existing `ui.nav` card.

```ts
/** Create a card containing a navigation pane. */
export interface State {
  /** The navigation groups contained in this pane. */
  items: NavGroup[]
  /** The name of the active (highlighted) navigation item. */
  value?: S
  /** Items that should be displayed at the bottom of the card. */
  secondary_items?: Component[]
  /** The card's title. */
  title?: S
  /** The card's subtitle. */
  subtitle?: S
  /** The logo displayed at the top. **/
  image?: S
  /** The user avatar displayed at the top. Mutually exclusive with image, title and subtitle. **/
  persona?: Component
  /** Card background color. Defaults to 'card'. */
  color?: 'card' | 'primary
}
```
Extending the existing card makes probably more sense to me, wdyt @lo5?

### PR DESCRIPTION
**Pull request by mturoci**
image
image
image
image

## Proposed API

```ts
/** Create a card containing a navigation pane. */
export interface State {
  /** The navigation groups contained in this pane. */
  items: NavGroup[]
  /** The name of the active (highlighted) navigation item. */
  value?: S
  /** The card's title. */
  title?: S
  /** The card's subtitle. */
  subtitle?: S
  /** The icon, displayed to the left. **/
  icon?: S
  /** The icon's color. **/
  icon_color?: S
  /** The logo displayed at the top. **/
  image?: S
  /** The user avatar displayed at the top. Mutually exclusive with image, title and subtitle. **/
  persona?: Component
  /** Items that should be displayed at the bottom of the card if items are not empty, otherwise displayed under subtitle. */
  secondary_items?: Component[]
  /** Card background color. Defaults to 'card'. */
  color?: 'card' | 'primary'
}
```

cc @lo5 for design review

Closes #1118

### CODE REVIEW

**Comment by shihan007** [comment]
Screenshot 2021-11-15 at 20 17 00i
@mturoc This layout is better. but logo takes too much space. it would be better if we can reduce the logo size so that we can show more menu items. 
If we can reduce the logo size and left align with title and subtitle would be great.

@sandruparo @shanaka-rajitha wdyt?

**Comment by lo5** [comment]
API and redesign looks great! 

Agree with @shihan007's comment above.

**Comment by shihan007** [comment]
@mturoci @lo5 btw it would be great if we can display logo, title and logged person in top navigation. Like we have added in the design. So we have space left on side navigation for menu items.
Screenshot 2021-11-16 at 10 28 30

cc: @sandruparo @shanaka-rajitha

**Comment by mturoci** [comment]
>@mturoc This layout is better. but the logo takes too much space. it would be better if we can reduce the logo size so that we can show more menu items.

Yes, this depends on the size of the logo you upload, you can upload a smaller logo if you need more space. I only added top boundaries - `max-height: 150px`, but you are right, it can be too much, will go with `100px` instead.

> reduce the logo size and left align with title and subtitle would be great.

Not sure if this looks better
image
than
image

**Comment by mturoci** [comment]
>btw it would be great if we can display logo, title and logged person in top navigation

Already done, see https://github.com/h2oai/wave/pull/378.

**Comment by shihan007** [comment]
@mturoci can set the logo size to 64px and middle align title with it ?  
If we are displaying  logo and profile in top nav do we need to display again in side nav too? 

cc: @lo5

**Comment by mturoci** [comment]
>can set the logo size to 64px

You can set it to whatever size you want.

> middle align title with it 

So back to the original implementation, right?

>If we are displaying logo and profile in top nav do we need to display again in side nav too?

No, it's unnecessary to display it in both side and top, better to pick just one.

**Comment by shihan007** [comment]
> You can set it to whatever size you want.

From system lets set the size to 40px ( I think 40px is enough) .  And align text like this. So every logo have a standard size of 40px
Screenshot 2021-11-16 at 17 05 26

**Comment by mturoci** [comment]
>From system lets set the size to 40px ( I think 40px is enough) . And align text like this. So every logo have a standard size of 40px

If an app dev wants it this way, topnav can be used, no need to force it for sidenav as well.

**Comment by shihan007** [comment]
@mturoci It's better to use same sizing for both top nav and side nav logos in consistency wise. By doing that we can save up space in the side nav to display more menu item which is the primary goal

**Comment by mturoci** [comment]
Why would I display the same logo twice in a single app?

**Comment by mturoci** [comment]
> By doing that we can save up space in the side nav to display more menu items which is the primary goal

* If you have plenty of nav items - use top nav with logo + sidebar without logo only with links.
* If you have just a few links, use just one. Either sidenav or top nav.

Design in this PR is suited for low content apps (majority of apps) so it's better to use the available space rather than have a lot of whitespace which doesn't look good.

**Comment by shihan007** [comment]
> Why would I display the same logo twice in a single app?

No not the same logo, I meant sizing

> * If you have plenty of nav items - use top nav with logo + sidebar without logo only with links.
> * If you have just a few links, use just one. Either sidenav or top nav.
> 
> Design in this PR is suited for low content apps (majority of apps) so it's better to use the available space rather than have a lot of whitespace which doesn't look good.

Apps like mlops have more menu items. Even though app have one or two many item it doesnt matter normally those menu items aligned to top and we can keep rest white space.

**Pull request merged**
