### PR TITLE
feat: Add more themes #696

### LINKED ISSUE #696: Include more light/dark themes
There are currently two themes bundled in. It's super-easy to ship more. Ship at least 10 more for 2021.

### PR DESCRIPTION
**Pull request by mturoci**
Themes are based on popular IDE / Slack themes. All credits included within code + future release blog post.

## winter-is-coming
winter-is-coming

## fuchasia
fuchasia

## monokai
monokai

## nature
nature

## nord
nord

## oceanic
oceanic

## one-dark-pro
One-dark-pro

## benext
image

## ember
ember

## kiwi
kiwi

## lighting
lighting

## solarized
solarized

@lo5 wdyt?

Closes #696

### CODE REVIEW

**Comment by geomodular** [comment]
Good job, Martin! My favorite is the `solarized` theme. Love it. But I have color vision deficiency, so that might add to it 🤷‍♂️ .

**Comment by lo5** [comment]
Nice! Overall, looks fine, but individual themes need some tweaking.

Needs improvement:

- (Major) The header in almost all cases needs to have a contrasting color compared to the primary color used in the body. e.g. if you compare these to themes in Slack, in each case, the header is desaturated if the primary color is saturated, or vice versa. Maybe have the design team spend some cycles on this?
- `ebnext`:  gray cards on a white background looks odd. Contrast needs adjustment (or reversed?).
- (Lower priority, but needs thought) The `spectrum` colors need to be adjusted to the theme if possible, otherwise the visualization colors may not sit well with the UI. One way to automate this is to set the saturation of each color in the spectrum to the saturation of the primary color (match the S in HSL/HSV - don't know which would work best - needs trial).
- Were these hand-coded, or did you write a script to map colors?

**Comment by mturoci** [comment]
Thanks for the review @lo5!

> (Major) The header in almost all cases needs to have a contrasting color compared to the primary color used in the body. e.g. if you compare these to themes in Slack, in each case, the header is desaturated if the primary color is saturated, or vice versa. Maybe have the design team spend some cycles on this?

Agree this might make sense for some cases, but currently, our header and sidenav support a `color` attribute - not released yet so can still be changed before `0.20`.

```ts
  /** Header background color. Defaults to 'primary'. */
  color?: 'card' | 'transparent' | 'primary'
```

The question is whether we want to

* add a new prop that will incorporate the saturation
* adjust `primary` prop to use the proposed saturation in the header - probably the best, but can cause confusion as this is the default so people will see their header color changed after upgrade
* saturate/desaturate both `card` and `primary` options - would need a change of the option names then
* remove the whole `color` attr and do not allow people to tweak it at all - use original primary and saturate/desaturate.

> ebnext: gray cards on a white background looks odd. Contrast needs adjustment (or reversed?).

Agree, will reverse them.

> (Lower priority, but needs thought) The spectrum colors need to be adjusted to the theme if possible, otherwise the visualization colors may not sit well with the UI. One way to automate this is to set the saturation of each color in the spectrum to the saturation of the primary color (match the S in HSL/HSV - don't know which would work best - needs trial).

Will experiment with it and update this PR.

> Were these hand-coded, or did you write a script to map colors?

These were generated by our `Theme Generator` Wave app, then I just copied over the resulting Fluent colors that were produced under the hood by our TS. Another option I was thinking about was to generate the Fluent palette dynamically on demand during app startup (same like we do for custom, user-defined themes), but ended up with a simple first iteration of this.

**Comment by mturoci** [comment]
> The header in almost all cases needs to have a contrasting color compared to the primary color used in the body. e.g. if you compare these to themes in Slack, in each case, the header is desaturated if the primary color is saturated, or vice versa.

I tried to play with saturation of the primary color according to the following formula:

```ts
fluentPrimary.s > 50 ? fluentPrimary.s - 30 : fluentPrimary.s + 30
```

basically increasing / decreasing saturation by a constant based on primary color saturation

The result:

image
image
image
image
image
image
image
image
image
image
image
image

Another alternative I was thinking about is to simply take the color that's used for the table header/footer and use it for the header (would need text color adjustments).

Also asked the design team for their input.

The API question still stands.

> The spectrum colors need to be adjusted to the theme

I basically took `saturation` of the primary color and set it to every spectrum color. Note that for the following screenshots, the header uses pure primary color (without saturation adjustments) to see what primary color was chosen and how it plays together with spectrum colors. All the examples come with 2 variants HSL(1) and HSV(2):

image
image

image
image

image
image

image
image

image
image

image
image

image
image

image
image

image
image

image
image

image
image

image
image

IMO `HSL` (first variant) seems to match better than `HSV`.

**Comment by shihan007** [comment]
@mturoci @lo5 We have provided a design for header with minimal attention. Let me know if we can implement the same and use for any app.

Screenshot 2022-01-19 at 10 31 59

https://xd.adobe.com/view/0790f950-abbd-41fa-b372-332295fd876f-52c3/screen/f4b9e6c7-6c86-445d-a598-fb37bcda5115/

**Comment by lo5** [comment]
@shihan007 Looks good, but we'll have to push it out to a future release (this PR is related to themes). 
Can you please file a separate issue indicating the changes?

**Review by lo5 — APPROVED** [review]
@mturoci Looks great! Good to merge and release for 0.20. We can always make minor tweaks to the colors in a future release.

**Comment by shihan007** [comment]
> @shihan007 Looks good, but we'll have to push it out to a future release (this PR is related to themes). Can you please file a separate issue indicating the changes?

@mturoci I created that header ticket referring this comment from Prithvi

**Pull request merged**
