### PR TITLE
Fix: form visibility

### LINKED ISSUE #484: Visible prop on textbox not working
via @5675sp 
#### Wave SDK Version, OS

0.10.0

#### Actual behavior

After setting `visible` prop as `False`, textbox component is visible nonetheless.

#### Expected behavior

Textbox should not be visible.

### LINKED ISSUE #817: Message bar visibility doesn't hide component
#### Wave SDK Version, OS
v0.15.0 in Chrome on Mac

#### Actual behaviour
`ui.message_bar` with `visible=False` still shows the background.

#### Expected behaviour
It should be hidden completely.

#### Steps to Reproduce
```python
ui.message_bar(type='success', text='Predictions successfully completed!', visible=False)
ui.message_bar(type='success', text='Predictions successfully completed!', visible=True)
```

Screenshot 2021-05-16 at 1 04 23 AM

Maybe related to #484 ?

### PR DESCRIPTION
**Pull request by mturoci**
Moved the visibility handling logic to parent form component instead of dealing with it at component level.

There was also a minor spacing issue - we applied `marginTop: 0` to `:not(:first-child)` selector. The problem is, this selector looks at the DOM (hidden elements are still present in the DOM), not whether the element is visible or not. I managed to fix it via CSS.

Closes #484
Closes #817

### CODE REVIEW

**Comment by lo5** [comment]
Any reason why this uses `visibility: hidden` instead of the previous `display: none`? 
Also, we should find a non-js solution to spacing.

**Comment by mturoci** [comment]
> Any reason why this uses `visibility: hidden` instead of the previous `display: none`?

Futurewise, `display: none` cannot be animated. This means that after resolving #229 (form components will be properly updated instead of recreated on props change), we can make toggled elements leave smoothly instead of snapping. Apart from that, there is not really much of a difference.

> Also, we should find a non-js solution to spacing.

I tried to look for something better, but can try harder.

**Comment by mturoci** [comment]
Found a pure CSS approach for spacing. Added custom data attr `data-visible` to get info whether the element is currently visible or not. Then used `> [data-visible="true"] ~ div'` to select all direct form elements that are preceded by visible elements. This is a working solution for "first **visual** child and onwards.

Also added the needed functionality to horizontal (inline) part.

**Comment by mturoci** [comment]
* Rebased.
* Replaced `visibility: hidden` with `display:none` as discussed.
* Added example demonstrating the feature.

https://user-images.githubusercontent.com/64769322/105163171-dcb09b80-5b13-11eb-814f-cd7077a0b241.mov


Needs discussion: @lo5 this approach will not work for cases when `visible` is defined on elements in `ui.buttons` as it creates its own wrapper at component level. A few ways to resolve this:
* Shouldn't `ui.buttons` be deprecated in favor of `ui.inline` or you left it there just for the sake of not introducing a breaking change?
* Special case it within `button` component.

**Comment by mturoci** [comment]
Rebased against current master.

**Review by lo5 — COMMENTED** [review]
This PR causes a breaking change: the `visible` attribute has been removed from the API.

**Comment by mturoci** [comment]
TBH I don't remember the reasoning why `visible` was removed from each component. Adding it back to API should cause no harm as it is used anyway.

**Comment by mturoci** [comment]
* rebased
* reverted back `visible` prop per component to avoid breaking change
* special cased the button component to allow using `visible` prop even inside `ui.buttons` component.

**Comment by mturoci** [comment]
Rebased.

**Comment by mtanco** [comment]
@mturoci seeing similar behavior for Toggles, would that be handled automatically in this PR too or should I open a separate issue?

image


Wave 0.16.0
```python
from h2o_wave import site, ui

page = site['/']

page['toggle'] = ui.form_card(
    box='4 4 4 4',
    items=[
        ui.toggle(name='hidden', label='You can\'t see me', visible=False),
        ui.toggle(name='shown', label='You can see me', visible=True),
    ]
)
page.save()
```

**Comment by mturoci** [comment]
@mtanco  This PR fixes visibility for all the form items at once so no need to open a new issue.

**Comment by lo5** [comment]
@mturoci - what would be the minimal fix for this bug (without changes to the generator, or introducing changes to launch.json, precommit.js, etc.)?

**Comment by mturoci** [comment]
The minimal changes are to move visibility handling logic from component scope to form scope. The generator is updated so that every form component has a consistent `visible` prop, but we can go with hardcoding it as it was before ofc.

**Comment by mturoci** [comment]
@lo5 rebased against current master, removed all the extra stuff that is not necessarily part of the fix, removed the generator tweaks and settled back to specifying `visible` per each component.

**Comment by psinger** [comment]
@mturoci What is the status of this issue? Will it be fixed soon? Thanks!

**Pull request merged**
