### PR TITLE
feat: generated docs showcase #699

### LINKED ISSUE #601: Fonts and Icons are not bundled
#### Wave SDK Version, OS

0.12.1 darwin

#### Actual behavior

Some fonts and icons are not bundled but instead fetched from the internet.
Fails in air-gapped environments.

#### Expected behavior

Every asset is bundled, no requests to the internet are made.

#### Steps To Reproduce

- Go offline
- Start wave tour
- Open devtools - network tab
- Open `localhost:10101/tour`
- Click through and notice failed requests

Some of those failed requests might be from the tour app dependencies which is out of the scope of this issue.
However, at least the Inter font is related to the core wave.

### LINKED ISSUE #699: Improve Showcase
Make the showcase app in `py/demo` similar in principle to the [Bootstrap](https://getbootstrap.com/docs/5.0/components/alerts/) docs - an app that serves three purposes:

1. An extensive showcase of what Wave is capable of.
2. A reference developers can use in addition to the the currrent "Tour" app ("How do I do that?").
3. (For contributors) - a development-time tool manually/visually test new cards/components or changes to existing ones. If we build up a comprehensive collection of every card/component variation, the next step would be to automate visual verification (based on #531).

**Tasks**
- [ ] Create one page per card (with all possible variations)
- [ ] Create one page per component (with all possible variations)
- [ ] Guide level docs
- [ ] :muscle: Compile and display code snippet into the page for copypasta convenience

### PR DESCRIPTION
**Pull request by mturoci**
This PR creates cards and components pages in the docs with autogenerated cropped screenshots:

https://user-images.githubusercontent.com/64769322/114204555-9cfe9080-9959-11eb-9418-a6b133bf1d57.mov

Flow:
* `tools/showcase` contains folders for components and cards `.md` files.
* The md files have to have **working** minimal code that will be rendered, screenshot and cropped.
* To trigger generate, simply cd to `tools/showcase` and run `make generate` (once `make setup` is run)

This can be later extended to also do visual testing comparisons.

I have first implemented this in NodeJS, but lacked sync support so switched to Python Playwright version.

The current browser used for taking images is Chromium.

@lo5 please lmk whether you wanted something like this. Once approved, I can start writing the docs with best practices and usage for each component/card (similar to https://getbootstrap.com/docs/5.0/components/alerts/). Or maybe this would be better suited for @sandruparo as some kind of design doc.

Closes #699

In order to remove flakiness, implemented #601 as part of visual testing.

Closes #601

### CODE REVIEW

**Comment by lo5** [comment]
PR looks awesome!

Browsers are not installed during `make setup`. Should this line be added?

    elp@ugh:~/git/h2oai/wave/tools/showcase (feat/issue-699)
    $ python -m playwright install
    Downloading chromium v857950 - 126.3 Mb [====================] 100% 0.0s
    chromium v857950 downloaded to /home/elp/.cache/ms-playwright/chromium-857950
    Downloading firefox v1238 - 73.4 Mb [====================] 100% 0.0s
    firefox v1238 downloaded to /home/elp/.cache/ms-playwright/firefox-1238
    Downloading webkit v1446 - 73.5 Mb [====================] 100% 0.0s
    webkit v1446 downloaded to /home/elp/.cache/ms-playwright/webkit-1446
    Downloading ffmpeg v1005 - 2.6 Mb [====================] 100% 0.0s
    ffmpeg v1005 downloaded to /home/elp/.cache/ms-playwright/ffmpeg-1005

Running as-is fails:

    elp@ugh:~/git/h2oai/wave (feat/issue-699)
    $ make docs
    cd py && make docs
    ...
    cd tools/showcase && make generate
    make[1]: Entering directory '/home/elp/git/h2oai/wave/tools/showcase'
    ./venv/bin/python showcase.py components
    make[2]: Entering directory '/home/elp/git/h2oai/wave'
    go run cmd/wave/main.go -web-dir ./ui/build -debug -editable
    2021/05/01 10:54:03 #
    2021/05/01 10:54:03 # ┌─────────────────────────┐
    2021/05/01 10:54:03 # │  ┌    ┌ ┌──┐ ┌  ┌ ┌──┐  │ H2O Wave
    2021/05/01 10:54:03 # │  │ ┌──┘ │──│ │  │ └┐    │ (version) (build)
    2021/05/01 10:54:03 # │  └─┘    ┘  ┘ └──┘  └─┘  │ © 2021 H2O.ai, Inc.
    2021/05/01 10:54:03 # └─────────────────────────┘
    2021/05/01 10:54:03 #
    2021/05/01 10:54:03 # {"address":":10101","t":"listen","webroot":"/home/elp/git/h2oai/wave/ui/build"}
    2021/05/01 10:54:04 * / {"d":[{"k":"form","d":{"view":"form","box":"1 1 1 1","items":[{"button":{"name":"button","label":"Button"}}]}}]}
    2021/05/01 10:54:04 # {"addr":"[::1]:56670","route":"/","t":"ui_add"}
    2021/05/01 10:54:04 # {"addr":"[::1]:56670","t":"ui_drop"}
    Traceback (most recent call last):
      File "/home/elp/git/h2oai/wave/tools/showcase/showcase.py", line 110, in <module>
        main()
      File "/home/elp/git/h2oai/wave/tools/showcase/showcase.py", line 98, in main
        generate_screenshots(browser)
      File "/home/elp/git/h2oai/wave/tools/showcase/showcase.py", line 57, in generate_screenshots
        make_snippet_screenshot(code, screenshot_name, browser)
      File "/home/elp/git/h2oai/wave/tools/showcase/showcase.py", line 40, in make_snippet_screenshot
        page.query_selector(f'[data-test="{card_name}"]').screenshot(path=path)
      File "/home/elp/git/h2oai/wave/tools/showcase/venv/lib/python3.9/site-packages/playwright/sync_api/_generated.py", line 2118, in screenshot
        self._sync(
      File "/home/elp/git/h2oai/wave/tools/showcase/venv/lib/python3.9/site-packages/playwright/_impl/_sync_base.py", line 103, in _sync
        return task.result()
      File "/home/elp/git/h2oai/wave/tools/showcase/venv/lib/python3.9/site-packages/playwright/_impl/_element_handle.py", line 224, in screenshot
        with open(path, "wb") as fd:
    FileNotFoundError: [Errno 2] No such file or directory: '../../website/docs/components/assets/button-0.png'
    make[2]: *** [Makefile:60: run] Terminated
    make[1]: *** [Makefile:7: generate] Error 1
    make[1]: Leaving directory '/home/elp/git/h2oai/wave/tools/showcase'
    make: *** [Makefile:71: docs] Error 2

Fix: `showcase.py` needs to create these dirs in advance.

    elp@ugh:~/git/h2oai/wave (feat/issue-699)
    $ mkdir -p website/docs/components/assets
    mkdir: created directory 'website/docs/components'
    mkdir: created directory 'website/docs/components/assets'

    elp@ugh:~/git/h2oai/wave (feat/issue-699)
    $ mkdir -p website/docs/cards/assets
    mkdir: created directory 'website/docs/cards'
    mkdir: created directory 'website/docs/cards/assets'

Minor improvement: Instead of top-level "Cards" and "Components", how about a "Showcase" entry right above "Examples", and putting all the cards and components directly under "Showcase"? The example code for the components is going to make it clear that they're intended to go inside the form/section card anyway.

Overall, `showcase.py` looks short and simple - love the direction this is taking!

**Comment by mturoci** [comment]
> Browsers are not installed during make setup

Not sure what you mean, these should be installed as part of a setup target in `tools/showcase` makefile which is included in the main `setup` task. Running `make setup` solves this for me. Are there any issues I should have a look at?

> showcase.py needs to create these dirs in advance

Good catch, added to `make setup` target.

> Instead of top-level "Cards" and "Components", how about a "Showcase" entry right above "Examples", and putting all the cards and components directly under "Showcase"?

Well, I think separating it on a root nav level makes the distinction between components and cards absolutely clear, but your proposal is fine as well - implemented in https://github.com/h2oai/wave/pull/726/commits/5ebe1f5617708cf63b6dafeff798925806894e7e

**Comment by lo5** [comment]
> Not sure what you mean, these should be installed as part of a setup target in tools/showcase makefile 

See my comment above. On Linux, `pip install playwright` is not enough, `python -m playwright install` was necessary.

**Comment by mturoci** [comment]
> On Linux, pip install playwright is not enough, python -m playwright install was necessary

Fixed in https://github.com/h2oai/wave/pull/726/commits/7b080167ad480ad05d4bd333c4cb9c29400232e8.

**Comment by mturoci** [comment]
Wrote the docs for all the components:

https://user-images.githubusercontent.com/64769322/134326384-14588aca-22bf-447e-b7f7-844ac6945eae.mov

The `.md` files are located in `tools/showcase/showcase` in case they need refinement.

The next step is going to be asking someone with DS background to write something sensible on plot part as I lack expertise in this area.

**Comment by mturoci** [comment]
Note: Don't forget to fix links to card examples in `0.19` blog post as part of this PR as well.

**Review by lo5 — DISMISSED** [review]
Awesome @mturoci! It would be great to ship this with v0.20.0.

**Pull request merged**
