### PR TITLE
feat: reduce form Message Bar padding

### LINKED ISSUE #1398: Reduce height of the message bar.
via @psinger @Far0n @Nayananga 

It seems like the new message bar design does not fit well into Wave apps and needs to have the overall height reduced.

Implementation note: Think about whether message_bar shouldn't be decoupled from notification_bar implementation-wise.

## Tmp CSS workaround

```py
from h2o_wave import main, app, Q, ui


@app('/')
async def serve(q: Q):
    # Use [data-test="form"] to scope styling to a particular card (in this case card with key "form").
    # Leave out the key if you want to style every message bars / notification_bars.
    style = '''
    [data-test="form"] .ms-MessageBar {
      padding-top: 8px;
      padding-bottom: 8px;
      min-height: 24px;
    }
    '''

    q.page['form'] = ui.form_card(box='1 1 5 5', items=[ui.message_bar(type='success', text='Text')])
    q.page['meta'] = ui.meta_card(box='', stylesheet=ui.inline_stylesheet(style))
    await q.page.save()

```

### PR DESCRIPTION
**Pull request by aalencar**
Notification bar

image

Message bar inside form card

image

closes #1398

### CODE REVIEW

**Comment by mturoci** [comment]
Current implementation accepts 8 params, but uses only 3 in common. Let's refactor into separate components for both message and notification bars accordingly.

**Comment by aalencar** [comment]
I don't think it's worth refactoring, there will be too much duplicate code for the styles.

`onDismiss`, `extraStyles`, `isMultiline`, and `size` don't introduce any tricky logic.

**Comment by mturoci** [comment]
> will be too much duplicate code for the styles

That's fine.

**Comment by aalencar** [comment]
@mturoci ready for review.

**Review by mturoci — CHANGES_REQUESTED** [review]
Thanks @aalencar!

* Please remove unused properties from `MessagebarProps`.
* There is a missing import for `wave` in `notification_bar`, probably merge conflict err.

Looking good otherwise!

**Comment by aalencar** [comment]
> Please remove unused properties from MessagebarProps.

done

> There is a missing import for wave in notification_bar, probably merge conflict err.

yes

Ready for review.

**Review by mturoci — APPROVED** [review]

**Pull request merged**
