### PR TITLE
style: center breadcrumb component vertically #337

### LINKED ISSUE #337: Tab Text Not Vertically Centered
This is a question not a bug per se. I noticed that the text in this tab isn't vertically centered. Is that expected? 

image

https://github.com/h2oai/wave-apps/pull/10

### PR DESCRIPTION
**Pull request by mturoci**
Closes #337

### CODE REVIEW

**Review by lo5 — APPROVED** [review]
Thanks @mturoci.

**Comment by mturoci** [comment]
Rebased.

**Review by lo5 — CHANGES_REQUESTED** [review]
Needs a rebase. Also, can we use the same strategy as https://github.com/h2oai/wave/commit/565b6f60c604970bb9d83ab2cc2e2a83774073fe? I'd like to avoid using `Fluent.Stack`.

**Comment by mturoci** [comment]
* Rebased
* The reason why this was not centered vertically was that Fluent's implementation set top margin to 11px and bottom margin to 1px. I have set them both to 15px instead (feel free to adjust as you see fit).

image

(The card has `CardEffect.Transparent`, I just temporarily removed in order to clearly show the centering in screenshot)

**Comment by lo5** [comment]
@mturoci - it's not centered. Better to remove Fluent's 11px top-margin. 

Screenshot from 2021-01-20 09-28-23

**Comment by mturoci** [comment]
The margin is already out. Are you sure you are running with latest client changes?
image

**Review by lo5 — APPROVED** [review]
I see it now - my bad. 
Thanks @mturoci!

**Pull request merged**
