### PR TITLE
feat: Make theme generator responsive

### PR DESCRIPTION
**Pull request by marek-mihok**
https://github.com/h2oai/wave/assets/23740173/0094afcb-448d-47b7-8dd3-98273e6c3ba2

### CODE REVIEW

**Comment by mturoci** [comment]
Thanks @marek-mihok! Could we put the sidebar into a side_panel which would be opened by a button in the header when it no longer fits the screen? Secondly, the sample app should not have the height constrained, but take as much space on the mobile as possible.

**Comment by marek-mihok** [comment]
> Thanks @marek-mihok! Could we put the sidebar into a side_panel which would be opened by a button in the header when it no longer fits the screen? Secondly, the sample app should not have the height constrained, but take as much space on the mobile as possible.

@mturoci is this what you imagine?

https://github.com/h2oai/wave/assets/23740173/f40381eb-02e2-46c9-b9eb-d2eb93671f1f

**Comment by mturoci** [comment]
Yes, that's exactly what I wanted. One last thing: the sample app looks cramped on mobile so would be better to clean it up, e.g. table and plot definitely do not have enough space so put them under each other and so on.

**Comment by marek-mihok** [comment]
> Yes, that's exactly what I wanted. One last thing: the sample app looks cramped on mobile so would be better to clean it up, e.g. table and plot definitely do not have enough space so put them under each other and so on.

@mturoci it's done, however duplicating of items was necessary.

**Pull request merged**
