### PR TITLE
Implement searchbar_card for wave

### PR DESCRIPTION
**Pull request by VijithaEkanayake**
searchbar_card can be used to horizontally align textbox and button on the requirement. Fixes: https://github.com/h2oai/wave/issues/372

### CODE REVIEW

**Comment by lo5** [comment]
Is there a strong reason for this to be in a card of its own? I'm not sure I understand the need for a separate search bar component (and nested/multiple search textboxes). The current textbox with a search icon can serve this purpose if we add `enter` key handling to it. 

What do you think @mturoci?

**Comment by VijithaEkanayake** [comment]
@lo5 The issue we face was, we had to use two different cards to submit the text-box values if we are not using triggers.
image
Basically wanted to have a textbox and a button next to each other and thought it is a very common use case that many people will definitely try to put stuff next to each other. For our case having a search icon with enter key handling also fine I guess.

**Comment by mturoci** [comment]
> The current textbox with a search icon can serve this purpose if we add enter key handling to it

Good suggestion. I see the point of this card only in solving the problem people were asking about since the birth of Wave itself - how to put a button next to a textbox.

I personally prefer searchbars with debounce / enter instead of buttons, but I can be biased as a software dev.

Nonetheless, if we still want to proceed with this card, I would do the following:
* Remove all the positioning and go with reasonable defaults - just put the button on the right side and align it. Right now this is not a searchbar implementation, but rather flexbox form I would say.
* Change the API to match textbox API.
* Add proper unit tests.

**Comment by lo5** [comment]
> I personally prefer searchbars with debounce / enter instead of buttons

Agree. Button-less search boxes are almost universal now - Chrome, Google Search, Github, etc., so I don't see a strong UX reason to put a button next to a textbox. Let's go with the enter key handling.

**Comment by VijithaEkanayake** [comment]
> > I personally prefer searchbars with debounce / enter instead of buttons
> 
> Agree. Button-less search boxes are almost universal now - Chrome, Google Search, Github, etc., so I don't see a strong UX reason to put a button next to a textbox. Let's go with the enter key handling.

Yeah, we can use enter key handling instead of separate card.

**Pull request closed without merging**
