### PR TITLE
Fixed bug in metadata where \n isn't recognized as a new line. 

### PR DESCRIPTION
**Pull request by MattiasOz**
**The PR fulfills these requirements:** (check all the apply)

- [x] It's submitted to the `main` branch.
- [x] When resolving a specific issue, it's referenced in the PR's title (e.g. `feat: Add a button #xxx`, where "xxx" is the issue number).
- [x] When resolving a specific issue, the PR description includes `Closes #xxx`, where "xxx" is the issue number.
- [x] If changes were made to `ui` folder, unit tests (`make test`) still pass.
- [ ] New/updated tests are included

### CODE REVIEW

**Comment by mturoci** [comment]
Hello @MattiasOz. Can you provide a further explanation about what was the actual problem you solved?

**Comment by MattiasOz** [comment]
I'm on arch and couldn't run any of the examples. The `make all` command would write 
`# Generated in hatch_build.py\n__platform__ = 'linux'\n__arch__ = 'amd64'`
exactly like that. The \n wasn't recognized as a new line making the whole file a comment.

**Comment by mturoci** [comment]
Makes sense, thanks for the clarification!

**Review by mturoci — APPROVED** [review]
LGTM.

**Comment by mturoci** [comment]
Let's see if the `-e` option does not break Ubuntu/Win e2e tests.

**Comment by mturoci** [comment]
As expected, it doesn't work on any of the other mainstream OSes since `-e` is an unknown option.

**Comment by mturoci** [comment]
Thus reverting.

**Pull request merged**
