### PR TITLE
chore: remove static examples from Tour #31

### LINKED ISSUE #31: Hard-code synthetic data in examples
The use of `Fake*` data generators make the plotting examples harder to decipher. 
Simplify by hard-coding data in the body of the examples.

### PR DESCRIPTION
**Pull request by mturoci**
Since all the static examples moved to our online docs (in #699), there is no need for duplication in Tour.

The proposal (originally by @lo5 quite a while ago) was to use our docs for showcase/static examples and the Tour app for interactive ones.

However, removing `synth` may not be the best idea since I find it useful for cases when one wants to generate real-looking mock data, for example in a table or dashboard examples without bloating the code, so I didn't remove it completely.

@lo5 wdyt?

Closes #31

### CODE REVIEW

**Comment by mtanco** [comment]
Feedback that a lot of users have been very confused by Synth. Can we use synth to generate a dataset and then that data comes with Tour?

**Comment by mturoci** [comment]
@mtanco would https://github.com/h2oai/wave/blob/master/py/demo/synthetic_data.py be a viable replacement for Synth?

**Comment by lo5** [comment]
There's an existing PR https://github.com/h2oai/wave/pull/443/files meant to remove `synth.py` (probably super-outdated by now to be of any use). 

For the examples to be more readable, it's better to embed the data directly in each example, like in the linked PR, especially  with columns/rows that represent some kind of real world data (instead of the random values generated by synth.py).

**Comment by mturoci** [comment]
Okay, what about the duplicates (basically all non-interactive examples)? Shall they be removed (like in this PR) or kept with hardcoded data?

**Comment by mturoci** [comment]
Based on yesterday's discussion, having duplicated examples across docs/tour is fine, the only thing needed to be done is to replace synth with reasonable data.

**Pull request closed without merging**
