### PR TITLE
feat: WidePlotCard. #1030

### LINKED ISSUE #1030: WidePlot card
design url: https://xd.adobe.com/view/119e73c2-d952-4760-8202-d36d3fc16016-44cd/specs/

image

## Proposed API:
image

### PR DESCRIPTION
**Pull request by mturoci**
image
image
image

## Proposed API

```ts
/** Create a wide plot card displaying a title, caption and a plot. */
interface State {
  /** The card's title. */
  title: S
  /** The card's caption, displayed below the title. */
  caption: S
  /** The card's plot. */
  plot: Plot
  /** The card's plot data. */
  data: Rec
}
```

possible to also add `events` if needed.

## Design questions

* What is the preferred text container width? I went with `200px` and let the plot take the rest of the space. We can also go for percentual ratio or something else.
* The space between text and plot seems to be too small (`8px` as per design)

Closes #1030

### CODE REVIEW

**Comment by shanaka-rajitha** [comment]
>What is the preferred text container width? I went with 200px and let the plot take the rest of the space. We can also go for percentual ratio or something else.

Preferred with is **274px**( 35% ) for text container and **454px**( 65% ) of the graph. The main container should be maximum **792px** as this is will add up to half the page width. 


>The space between text and plot seems to be too small (8px as per design)

Lets increase it to **16px** as the padding.

CC @mturoci

**Comment by mturoci** [comment]
> Preferred with is **274px**( 35% ) for text container and **454px**( 65% ) of the graph. The main container should be maximum **792px** as this is will add up to half the page width. 

The card can be any width / height so will go with percents 35:65 if that's fine.

> Lets increase it to 16px as the padding.

Will do.

**Comment by sandruparo** [comment]
cc - @dulajra @VijithaEkanayake

**Review by lo5 — APPROVED** [review]
Looks great!

**Pull request merged**
