### PR TITLE
#2047 - Future variable found a float expected an int, changed line 29 to int()

### PR DESCRIPTION
**Pull request by laneo1986**
**The PR fulfills these requirements:** (check all the apply)

- [ ] It's submitted to the `main` branch.
- [ ] When resolving a specific issue, it's referenced in the PR's title (e.g. `feat: Add a button #xxx`, where "xxx" is the issue number).
- [ ] When resolving a specific issue, the PR description includes `Closes #xxx`, where "xxx" is the issue number.
- [ ] If changes were made to `ui` folder, unit tests (`make test`) still pass.
- [ ] New/updated tests are included

### CODE REVIEW

**Review by mturoci — CHANGES_REQUESTED** [review]
Thanks @laneo1986. Please rerequest the review once all the errors are resolved so that I can do a bulk review instead of one by one.

**Comment by laneo1986** [comment]
> Thanks @laneo1986. Please rerequest the review once all the errors are resolved so that I can do a bulk review instead of one by one.

Apologies, will do that

**Comment by mturoci** [comment]
@laneo1986 are you still working on this or can I close the PR?

**Comment by laneo1986** [comment]
I'm no longer working on this apologies

**Pull request closed without merging**
